### PR TITLE
Merge pull request #1 from mate-academy/master

### PR DESCRIPTION
**Pull request by mrogozhinskaya**
- [DEMO LINK](https://mrogozhinskaya.github.io/layout_stars/)
- [TEST REPORT LINK](https://mrogozhinskaya.github.io/layout_stars/report/html_report/)

### CODE REVIEW

**Review by OleziO — CHANGES_REQUESTED** [review]
Add files to your PR

**Comment by mrogozhinskaya** [comment]
- [DEMO LINK](https://mrogozhinskaya.github.io/layout_stars/)
- [TEST REPORT LINK](https://mrogozhinskaya.github.io/layout_stars/report/html_report/)

**Review by mrogozhinskaya — COMMENTED** [review]
- [DEMO LINK](https://mrogozhinskaya.github.io/layout_stars/)
- [TEST REPORT LINK](https://mrogozhinskaya.github.io/layout_stars/report/html_report/)

**Comment by mrogozhinskaya** [comment]
- [DEMO LINK](https://mrogozhinskaya.github.io/layout_stars/)
- [TEST REPORT LINK](https://mrogozhinskaya.github.io/layout_stars/report/html_report/)

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
pull request should be from [develop](mrogozhinskaya:develop) branch
it is reason why zero files changed
Screenshot from 2023-06-27 09-53-53
Screenshot from 2023-06-27 09-53-33

**Comment by mrogozhinskaya** [comment]
Дякую, створила новий pull request from mrogozhinskaya:develop branch.
- [DEMO LINK](https://mrogozhinskaya.github.io/layout_stars/)
- [TEST REPORT LINK](https://mrogozhinskaya.github.io/layout_stars/report/html_report/)

**Review by OleziO — CHANGES_REQUESTED** [review]
Empty PR. Add some files to PR.
image

**Pull request closed without merging**
