### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by DevWashiington**
- [DEMO LINK](https://<devwashiington>.github.io/layout_stars/)
- [TEST REPORT LINK](https://<devwashiington>.github.io/layout_stars/report/html_report/)

### CODE REVIEW

**Comment by DevWashiington** [comment]
- [DEMO LINK](https://<DevWashiington>.github.io/layout_stars/)
- [TEST REPORT LINK](https://<DevWashiington>.github.io/layout_stars/report/html_report/)

**Comment by DevWashiington** [comment]
- [DEMO LINK](https://<DevWashiington>.github.io/layout_stars/)
- [TEST REPORT LINK](https://<DevWashiington>.github.io/layout_stars/report/html_report/)

**Comment by YriKm** [comment]
https://YriKm.github.io/layout_stars/report/html_report
https://YriKm.github.io/layout_stars/

**Comment by Arsenii34** [comment]
- [DEMO LINK](https://Arsenii34.github.io/layout_stars/)
- [TEST REPORT LINK](https://Arsenii34.github.io/layout_stars/report/html_report/)

**Comment by Alessandro15160** [comment]
- [DEMO LINK](https://Alessandro15160.github.io/layout_stars/)
- [TEST REPORT LINK](https://Alessandro15160.github.io/layout_stars/report/html_report/)

**Comment by souzasfelipe** [comment]
develop

**Pull request closed without merging**
