### PR TITLE
add task solution

### PR DESCRIPTION
**Pull request by ydashko**
- [DEMO LINK](https://ydashko.github.io/layout_stars/)
- [TEST REPORT LINK](https://ydashko.github.io/layout_stars/report/html_report/)

### CODE REVIEW

**Review by anstsot — CHANGES_REQUESTED** [review]
Looks good from a code perspective but your demo and report are empty. could you check it, please?
If you have any questions, feel free to ask them in the `fe_chat`

**Comment by ydashko** [comment]
- [DEMO LINK](https://ydashko.github.io/layout_stars/)
- [TEST REPORT LINK](https://ydashko.github.io/layout_stars/report/html_report/)

**Comment by ydashko** [comment]
Yeah somehow they do not show anything, i did tests again and now they are not passing via npm test command

**Comment by ydashko** [comment]
- [DEMO LINK](https://ydashko.github.io/layout_stars/)
- [TEST REPORT LINK](https://ydashko.github.io/layout_stars/report/html_report/)

**Comment by ydashko** [comment]
- [DEMO LINK](https://ydashko.github.io/layout_stars/)
- [TEST REPORT LINK](https://ydashko.github.io/layout_stars/report/html_report/)

**Pull request closed without merging**
