### PR TITLE
star project

### PR DESCRIPTION
**Pull request by BOHDANLIUYUI**
[DEMO LINK](https://BOHDANLIUYUI.github.io/layout_stars/)
 [TEST REPORT LINK](https://liuty.github.io/layout_stars/report/html_report/)

### CODE REVIEW

**Review by tetiana-ivanchenko — CHANGES_REQUESTED** [review]
add demo and test report links

**Comment by BOHDANLIUYUI** [comment]
> add demo and test report links
image

i did

**Comment by BOHDANLIUYUI** [comment]
> add demo and test report links

[DEMO LINK](https://BOHDANLIUYUI.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://BOHDANLIUYUI.github.io/layout_moyo-header/report/html_report/)

**Review by tetiana-ivanchenko — CHANGES_REQUESTED** [review]
check the demo links and test report you add in the PR description, they are wrong

**Review by etojeDenys — CHANGES_REQUESTED** [review]
you added the wrong links(from another task), please change it or feel free to ask about it in the slack chat

**Pull request closed without merging**
